/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ResumeV2LazyImport = createFileRoute('/resume-v2')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ResumeV2LazyRoute = ResumeV2LazyImport.update({
  id: '/resume-v2',
  path: '/resume-v2',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/resume-v2.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/resume-v2': {
      id: '/resume-v2'
      path: '/resume-v2'
      fullPath: '/resume-v2'
      preLoaderRoute: typeof ResumeV2LazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/resume-v2': typeof ResumeV2LazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/resume-v2': typeof ResumeV2LazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/resume-v2': typeof ResumeV2LazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/resume-v2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resume-v2'
  id: '__root__' | '/' | '/resume-v2'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ResumeV2LazyRoute: typeof ResumeV2LazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ResumeV2LazyRoute: ResumeV2LazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/resume-v2"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/resume-v2": {
      "filePath": "resume-v2.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
