import { geoGraticule10, geoOrthographic, geoPath, type GeoProjection } from 'd3-geo'
import type { Feature, FeatureCollection, MultiLineString, MultiPolygon } from 'geojson'
import { useEffect, useLayoutEffect, useRef, useState, type PointerEvent } from 'react'
import { feature, mesh } from 'topojson-client'
import type { GeometryCollection, Topology } from 'topojson-specification'
import landTopology from 'world-atlas/land-110m.json'
import { LOCATIONS, RACES, type LocationId } from '../data/races.ts'
import { useReducedMotion } from '../hooks/useReducedMotion.ts'
import styles from './Globe.module.css'
import {
  dragRotation,
  easeInOutCubic,
  interpolateView,
  isVisible,
  normalizeLng,
  sameView,
  targetView,
  viewDuration,
  viewModeFor,
  type Frame,
  type Rotation,
  type View,
  type ViewMode,
} from './geo.ts'

const topology = landTopology as unknown as Topology<{ land: GeometryCollection }>
const land = feature(topology, topology.objects.land)
const graticule = geoGraticule10()

/** Layers shown only while zoomed into the US. */
type Detail = { states: MultiLineString; borders: MultiLineString; lakes: MultiPolygon }

let detailPromise: Promise<Detail> | null = null

/**
 * Lazy: ~115 KB of states plus ~40 KB of North America. State borders are
 * interior only, so they never fight the 110m coastline. north-america.json
 * (international borders and large lakes, from Natural Earth) is generated by
 * scripts/build-north-america.mjs.
 */
function loadDetail() {
  detailPromise ??= Promise.all([import('us-atlas/states-10m.json'), import('./north-america.json')]).then(
    ([{ default: statesJson }, { default: northAmerica }]) => {
      const topo = statesJson as unknown as Topology<{ states: GeometryCollection }>
      const [borders, lakes] = (northAmerica as unknown as FeatureCollection).features as [
        Feature<MultiLineString>,
        Feature<MultiPolygon>,
      ]
      return {
        states: mesh(topo, topo.objects.states, (a, b) => a !== b),
        borders: borders.geometry,
        lakes: lakes.geometry,
      }
    },
  )
  return detailPromise
}

type Marker = { id: LocationId; city: string; dnfOnly: boolean }

const MARKERS: Marker[] = (Object.keys(LOCATIONS) as LocationId[]).map((id) => {
  const { city } = LOCATIONS[id]
  const races = RACES.filter((r) => r.locationId === id)
  return { id, city, dnfOnly: races.every((r) => r.outcome.status === 'dnf') }
})

export type MarkerShape = 'dot' | 'ring' | 'diamond'

type Props = {
  activeLocationId: LocationId | null
  activeShape: MarkerShape
  highlightedLocationId: LocationId | null
  onMarkerClick: (id: LocationId) => void
  onMarkerHover: (id: LocationId | null) => void
}

type Drag = { pointerId: number; x: number; y: number; start: Rotation; moved: boolean; lockTilt: boolean }

const EMPTY_FRAME: Frame = { x: 0, y: 0, w: 0, h: 0 }
const DRAG_THRESHOLD = 4
const LABEL_OFFSET = 13

// View changes bypass React: this writes straight to the DOM. React owns
// only data-active and data-highlighted on markers.
function draw(svg: SVGSVGElement | null, projection: GeoProjection, view: View, frame: Frame, detail: Detail | null) {
  if (!svg) return
  const { rotation } = view
  projection.rotate(rotation).scale(view.scale).translate(view.translate)
  const path = geoPath(projection)
  const layer = (name: string) => svg.querySelector(`[data-layer="${name}"]`)
  layer('sphere')?.setAttribute('d', path({ type: 'Sphere' }) ?? '')
  layer('graticule')?.setAttribute('d', path(graticule) ?? '')
  layer('land')?.setAttribute('d', path(land) ?? '')
  if (detail) {
    layer('lakes')?.setAttribute('d', path(detail.lakes) ?? '')
    layer('states')?.setAttribute('d', path(detail.states) ?? '')
    layer('countries')?.setAttribute('d', path(detail.borders) ?? '')
  }
  for (const el of svg.querySelectorAll<SVGGElement>('[data-location-id]')) {
    const { lat, lng } = LOCATIONS[el.dataset.locationId as LocationId]
    const visible = isVisible([lng, lat], rotation)
    const [x, y] = projection([lng, lat]) ?? [0, 0]
    el.setAttribute('transform', `translate(${x.toFixed(1)},${y.toFixed(1)})`)
    el.setAttribute('visibility', visible ? 'visible' : 'hidden')
    el.dataset.visible = String(visible)
    // Labels near the frame's right edge flip to the left of their marker.
    const label = el.querySelector('text')
    if (label) {
      const flip = x + LABEL_OFFSET + label.getComputedTextLength() > frame.x + frame.w - 4
      label.setAttribute('x', String(flip ? -LABEL_OFFSET : LABEL_OFFSET))
      label.setAttribute('text-anchor', flip ? 'end' : 'start')
    }
  }
  svg.dataset.rotation = `${normalizeLng(rotation[0]).toFixed(1)},${rotation[1].toFixed(1)}`
}

function setAnimating(svg: SVGSVGElement | null, animating: boolean) {
  if (svg) svg.dataset.animating = String(animating)
}

function setMode(svg: SVGSVGElement | null, mode: ViewMode) {
  if (svg) svg.dataset.view = mode
}

export function Globe({ activeLocationId, activeShape, highlightedLocationId, onMarkerClick, onMarkerHover }: Props) {
  const reducedMotion = useReducedMotion()
  const figureRef = useRef<HTMLElement>(null)
  const svgRef = useRef<SVGSVGElement>(null)
  const [projection] = useState(() => geoOrthographic())
  // On desktop the svg covers the viewport; the figure is the box views fit in.
  const frameRef = useRef<Frame>(EMPTY_FRAME)
  const viewRef = useRef<View>(targetView(null, EMPTY_FRAME))
  const detailRef = useRef<Detail | null>(null)
  const activeRef = useRef(activeLocationId)
  const rafRef = useRef(0)
  const dragRef = useRef<Drag | null>(null)
  const suppressClickRef = useRef(false)

  const redraw = () => draw(svgRef.current, projection, viewRef.current, frameRef.current, detailRef.current)

  const cancelFrame = () => {
    cancelAnimationFrame(rafRef.current)
    setAnimating(svgRef.current, false)
  }

  useLayoutEffect(() => {
    const svg = svgRef.current
    const figure = figureRef.current
    if (!svg || !figure) return
    setAnimating(svg, false)
    setMode(svg, 'globe')
    const observer = new ResizeObserver(() => {
      const outer = svg.getBoundingClientRect()
      const inner = figure.getBoundingClientRect()
      frameRef.current = { x: inner.left - outer.left, y: inner.top - outer.top, w: inner.width, h: inner.height }
      // A running fly re-targets every frame; otherwise refit, but keep any dragged rotation.
      if (svg.dataset.animating === 'true') return
      const { scale, translate } = targetView(activeRef.current, frameRef.current)
      viewRef.current = { rotation: viewRef.current.rotation, scale, translate }
      draw(svg, projection, viewRef.current, frameRef.current, detailRef.current)
    })
    // Any viewport change resizes the fixed svg, which also catches the column moving.
    observer.observe(svg)
    observer.observe(figure)
    return () => {
      observer.disconnect()
      cancelAnimationFrame(rafRef.current)
    }
  }, [projection])

  // Borders and lakes load the first time a US race is active.
  useEffect(() => {
    if (viewModeFor(activeLocationId) !== 'us' || detailRef.current) return
    let cancelled = false
    void loadDetail().then((detail) => {
      if (cancelled) return
      detailRef.current = detail
      draw(svgRef.current, projection, viewRef.current, frameRef.current, detail)
    })
    return () => {
      cancelled = true
    }
  }, [activeLocationId, projection])

  // Fly to the active location.
  useEffect(() => {
    activeRef.current = activeLocationId
    const svg = svgRef.current
    if (!activeLocationId || !svg) return
    const goal = () => targetView(activeLocationId, frameRef.current)
    const from = viewRef.current
    cancelAnimationFrame(rafRef.current)
    setMode(svg, viewModeFor(activeLocationId))
    if (reducedMotion || sameView(from, goal()) || from.scale === 0) {
      viewRef.current = goal()
      setAnimating(svg, false)
      draw(svg, projection, viewRef.current, frameRef.current, detailRef.current)
      return
    }
    const duration = viewDuration(from, goal())
    const start = performance.now()
    setAnimating(svg, true)
    const step = (now: number) => {
      const t = Math.min(1, (now - start) / duration)
      // The goal is recomputed each frame so a resize mid-flight lands correctly.
      viewRef.current = t < 1 ? interpolateView(from, goal())(easeInOutCubic(t)) : goal()
      draw(svg, projection, viewRef.current, frameRef.current, detailRef.current)
      if (t < 1) rafRef.current = requestAnimationFrame(step)
      else setAnimating(svg, false)
    }
    rafRef.current = requestAnimationFrame(step)
  }, [activeLocationId, reducedMotion, projection])

  const onPointerDown = (e: PointerEvent<SVGSVGElement>) => {
    if (e.button !== 0) return
    cancelFrame()
    dragRef.current = {
      pointerId: e.pointerId,
      x: e.clientX,
      y: e.clientY,
      start: viewRef.current.rotation,
      moved: false,
      // On touch, vertical swipes belong to the page (touch-action: pan-y).
      lockTilt: e.pointerType !== 'mouse',
    }
  }

  const onPointerMove = (e: PointerEvent<SVGSVGElement>) => {
    const drag = dragRef.current
    if (!drag || drag.pointerId !== e.pointerId) return
    const dx = e.clientX - drag.x
    const dy = e.clientY - drag.y
    if (!drag.moved) {
      if (Math.hypot(dx, dy) <= DRAG_THRESHOLD) return
      if (drag.lockTilt && Math.abs(dy) > Math.abs(dx)) {
        // A vertical touch gesture is a page scroll, not a drag.
        dragRef.current = null
        return
      }
      drag.moved = true
      e.currentTarget.dataset.dragging = 'true'
      // Captured lazily so that a plain tap still clicks the marker under it.
      e.currentTarget.setPointerCapture(e.pointerId)
    }
    viewRef.current = { ...viewRef.current, rotation: dragRotation(drag.start, dx, dy, viewRef.current.scale, drag.lockTilt) }
    cancelAnimationFrame(rafRef.current)
    rafRef.current = requestAnimationFrame(redraw)
  }

  const endDrag = (e: PointerEvent<SVGSVGElement>) => {
    const drag = dragRef.current
    if (!drag || drag.pointerId !== e.pointerId) return
    dragRef.current = null
    delete e.currentTarget.dataset.dragging
    if (drag.moved) {
      suppressClickRef.current = true
      setTimeout(() => (suppressClickRef.current = false))
    }
  }

  const ordered = [...MARKERS].sort((a, b) => Number(a.id === activeLocationId) - Number(b.id === activeLocationId))

  return (
    <figure ref={figureRef} className={styles.figure}>
      <figcaption className="visually-hidden">Globe showing race locations; follows the race list</figcaption>
      <svg
        ref={svgRef}
        className={styles.svg}
        aria-hidden="true"
        onPointerDown={onPointerDown}
        onPointerMove={onPointerMove}
        onPointerUp={endDrag}
        onPointerCancel={endDrag}
      >
        <defs>
          <radialGradient id="globe-shade" cx="38%" cy="32%" r="75%">
            <stop offset="0%" className={styles.shadeLight} />
            <stop offset="100%" className={styles.shadeDark} />
          </radialGradient>
        </defs>
        <path data-layer="sphere" className={styles.sphere} />
        <path data-layer="graticule" className={styles.graticule} />
        <path data-layer="land" className={styles.land} />
        <g data-layer="detail" className={styles.detail}>
          <path data-layer="lakes" className={styles.lakes} />
          <path data-layer="states" className={styles.states} />
          <path data-layer="countries" className={styles.countries} />
        </g>
        {ordered.map((marker) => {
          const active = marker.id === activeLocationId
          const shape: MarkerShape = active ? activeShape : marker.dnfOnly ? 'ring' : 'dot'
          const r = active ? 8 : 5
          return (
            <g
              key={marker.id}
              className={styles.marker}
              data-location-id={marker.id}
              data-shape={shape}
              data-active={active}
              data-highlighted={marker.id === highlightedLocationId}
              onPointerEnter={(e) => {
                if (e.pointerType === 'mouse') onMarkerHover(marker.id)
              }}
              onPointerLeave={(e) => {
                if (e.pointerType === 'mouse') onMarkerHover(null)
              }}
              onClick={() => {
                if (!suppressClickRef.current) onMarkerClick(marker.id)
              }}
            >
              <circle className={styles.hit} r={14} />
              {shape === 'diamond' ? (
                <rect className={styles.dot} x={-r * 0.8} y={-r * 0.8} width={r * 1.6} height={r * 1.6} transform="rotate(45)" />
              ) : (
                <circle className={styles.dot} r={r} />
              )}
              {active && (
                <text className={styles.label} x={LABEL_OFFSET} y={5}>
                  {marker.city}
                </text>
              )}
            </g>
          )
        })}
      </svg>
    </figure>
  )
}
